### PR TITLE
matlab-snippets

### PR DESCRIPTION
**Pull request by MistressOfUniverses**
A small package for espanso with triggers for headers and code snippets I constantly use in MATLAB

### CODE REVIEW

**Comment by smeech** [comment]
A simple package with one global variable, five triggers and two forms. No shell commands, scripts or malicious code.

A number of problems, however. The CI generates the following errors:
```
Check: missing_mandatory_files
 ->: expected file 'package.yml' to be present inside package: matlab-snippets, but found none. File should be present in path: packages/matlab-snippets/0.1.0/package.yml
Check: incoherent_path
 ->: while parsing a flow sequence
  in "packages/matlab-snippets/0.1.0/_manifest.yml", line 6, column 7
expected ',' or ']', but got '<scalar>'
  in "packages/matlab-snippets/0.1.0/_manifest.yml", line 6, column 16
Check: missing_manifest_fields
 ->: while parsing a flow sequence
  in "packages/matlab-snippets/0.1.0/_manifest.yml", line 6, column 7
expected ',' or ']', but got '<scalar>'
  in "packages/matlab-snippets/0.1.0/_manifest.yml", line 6, column 16
Check: invalid_yaml
 ->: invalid YAML detected in file: packages/matlab-snippets/0.1.0/_manifest.yml, please make sure the file is formatted correctly. If you're unsure of the error, you can use http://www.yamllint.com/ to validate it.
Error: while parsing a flow sequence
  in "packages/matlab-snippets/0.1.0/_manifest.yml", line 6, column 7
expected ',' or ']', but got '<scalar>'
  in "packages/matlab-snippets/0.1.0/_manifest.yml", line 6, column 16
```
Essentially:

- `matlab-snippets.yml` needs to be renamed to `package.yml`
- The `tags:` items in `_manifest.yml` need to be separated by _commas_, not periods. 
- Additionally, I suggest removing "v0.1.0", "snippets" & "espanso", and add "math" and any other relevant tags from the examples at https://hub.espanso.org/search, to make the package easier to find there.
- We're having problems with incomplete hub merging of packages whose `_manifest.yml` doesn't contain a `homepage:` item - would you kindly add one, even if it just points to https://github.com/MistressOfUniverses/hub/tree/MATLAB-snippets-package, please?
- The forms each contain redundant lines where the `text:` item refers to an absent form field `[[text]]`. These can be removed:
```yml
    form_fields:
      text:
        multiline: true
```
- The indentation of the descriptions of the triggers in README.md causes markdown to format them as code, which means the lines don't wrap on-screen, and I think this makes them difficult to read. May I suggest formatting them differently? - have a look at other packages in https://github.com/espanso/hub/tree/main/packages for examples.

I'm sorry there's a bit of work to do before we can merge this package into the Hub but do let me know if I can help further!

**Comment by smeech** [comment]
Are you likely to make the above changes so we can merge the package, or have you lost interest?

Let me know if you need any help.

**Comment by MistressOfUniverses** [comment]
Hi, I currently have lost interest as I have been very busy with college. Thanks for asking.

**Comment by smeech** [comment]
> Hi, I currently have lost interest as I have been very busy with college. Thanks for asking.

That's quite understandable. Thank you for letting me know. 
I'll close this for now rather than keep it hanging, but you're very welcome to come back to it if you feel the urge!

With best wishes. Enjoy your studies!

**Pull request closed without merging**
