### PR TITLE
Typofixer package for 4 languages

### PR DESCRIPTION
**Pull request by Mte90**
Ref: https://github.com/Mte90/espanso-typofixer

### CODE REVIEW

**Comment by federico-terzi** [comment]
@Mte90 Looks great! Before we merge, we need to add a README.md file to each of them :)

**Comment by Mte90** [comment]
Readme added

**Comment by federico-terzi** [comment]
Looks amazing, thank you! 🚀

**Comment by Mte90** [comment]
```
[ERROR] unable to load match group "/home/mte90/.config/espanso/match/packages/typofixer-en/package.yml"

Caused by:
    0: failed to parse YAML match group
    1: matches[0][0]: invalid type: map, expected a string at line 4 column 12
```

So seems that there is an issue when I am downloading that the action there didn't spotted.
I am already working on a fix

**Comment by Mte90** [comment]
```
Caused by:
    0: failed to parse YAML match group
    1: matches[0].propagate_case: invalid type: string "true", expected a boolean at line 6 column 19
```

So it seems that is not still valid for espanso...

**Pull request merged**
