### PR TITLE
Norwegian characters, accents and quote marks

### PR DESCRIPTION
**Pull request by oaustegard**
Let's hope this benefits both Norwegian Espanso users on US keyboards...

### CODE REVIEW

**Comment by oaustegard** [comment]
Also see #21

**Comment by federico-terzi** [comment]
Hey @oaustegard,

Sorry for the late reply! The package looks amazing, just a couple of things before we can proceed:

* The package files should be located inside a folder called `0.1.0` inside the package folder (see other packages as example)
* If you run `git pull origin main` and repush, you should get the CI to automatically check the format the next time :)

Thanks!

**Comment by oaustegard** [comment]
Ah, foiled by the auto-collapsing of empty folders by both Github and VS Code, never noticed the intermediate version folders...

Updated -- not sure the CI format check is held up by this? 
image

**Comment by oaustegard** [comment]
@federico-terzi  it appears you added #24 (great concept!) and #28 which failed when it attempted to automatically run n my local fork of the repo. See https://github.com/oaustegard/hub/runs/6413059244?check_suite_focus=true and 
image

I'm unfamiliar with GH Actions in general and the specific functions of your publish_packages.py in particular so I can't quite figure out what part failed, but **should publish-packages.yml be running in contributors' forked repos in the first place?**

**Comment by federico-terzi** [comment]
@oaustegard Looks great! Thanks :)

**Comment by oaustegard** [comment]
Great! Just in time for [søttende mai](https://en.wikipedia.org/wiki/Constitution_Day_(Norway))!

**Comment by federico-terzi** [comment]
@oaustegard Yey :D

**Pull request merged**
