### PR TITLE
Update aspnetboilerplate-aspzerohub package (v.0.1.1)

### PR DESCRIPTION
**Pull request by canmavi**
- New fields were added, 
- Visual Studio was prevented from making changes to the copied value,
- Trigger values ​​were changed,
- Warning added to README file to avoid problems for some users.

### CODE REVIEW

**Comment by smeech** [comment]
An update to a simple trigger/replace package. No shell, script, or potentially malicious code.

I would be inclined to remove the "aspnetboilerplate-espanso", "aspnetzerohub-espanso", and "aspnetboilerplate-aspzerohub-espanso" tags from `_manifest.yml` as they don't add anything useful in the [Hub](https://hub.espanso.org/aspnetboilerplate-aspzerohub) to the "code", "aspnetboilerplate", and "aspnetzero" tags (which should be kept).

Would it be reasonable to remove the instances of `force_clipboard: true`?:

1. `force_clipboard:` is now deprecated in favour of the more flexible [`force_mode:`](https://espanso.org/docs/matches/basics/#injection-mechanism) options.  
2. the `force_` keys are primarily intended for testing particular environments and won't suit everyone if they're fixed. 
3. `backend:` settings are best set according to individual user requirement, in `config/default.yml` and/or app-specific configurations.

Thank you for the update!

**Comment by canmavi** [comment]
Hi, thanks for the answer.

"aspnetboilerplate-espanso", "aspnetzerohub-espanso", and "aspnetboilerplate-aspzerohub-espanso" can also be removed, so I will edit it again.

We are testing this package on several computers, in some cases, when replacing, the first character of the copied value is uppercase, sometimes we noticed that replace does not work at all and this causes problems. So while looking for a solution to this problem, I used force_clipboard since it was written in this way in old issues. I noticed that the problem was solved when I set "Backend", I had not noticed this. I will add this as a note and update.

Thanks

**Comment by canmavi** [comment]
I **updated** it, you can check it.

Thanks

**Comment by smeech** [comment]
Thank you. I have taken the liberty of amending README.md slightly.

Merged.

**Pull request merged**
