### PR TITLE
New "air-codes" espanso package

### PR DESCRIPTION
**Pull request by cl3mcg**
Hello,
I would like to submit a package I have created to the Espanso hub.
This package is related to airports and airlines.

The **air-codes** package can become a resource for air transportation data, offering convenient access to:
- Properly formatted airport names and locations based on their IATA codes.
- Accurate airline names associated with their respective IATA 2-letter airline identifiers.

Don't hesitate to review the _readme.md_ file for further information.
If needed, don't hesitate to contact me.

Thank you.

### CODE REVIEW

**Review by smeech — COMMENTED** [review]
A large package of airlines and airports.
No `cmd: `, `: shell`, `: script`, or malicious code, as far as I can see.
What are the repeated labels for? They increase the length of the code and prevent one using Espanso's search box facility to find items.
Could be safely merged.

**Comment by cl3mcg** [comment]
> A large package of airlines and airports. No `cmd: `, `: shell`, `: script`, or malicious code, as far as I can see. What are the repeated labels for? They increase the length of the code and prevent one using Espanso's search box facility to find items, which will narrow appeal. Could be safely merged.

Hello and thank you for reviewing my pull request.
Based on your feedback, I've removed the extraneous labels for each trigger to declutter Espanso's search box.
Appreciate your guidance!

**Comment by smeech** [comment]
Thank you - I think that will make it much more useful.
All checks passed with your update.
Rechecked no `cmd: `, `: shell`, `: script`, or malicious code. (Our safety check)
Just waiting for someone else to review, as I think it's important that more than one person is involved, but should be merged soon.

**Comment by AucaCoyan** [comment]
Yup all good!

**Pull request merged**
