### PR TITLE
New package: Better Typography

### PR DESCRIPTION
**Pull request by jwliles**
This package has been useful to me for a few months now. I figured somebody else may find it useful.

### CODE REVIEW

**Comment by jwliles** [comment]
I have fixed the typos pointed out in the CI output.

**Comment by federico-terzi** [comment]
Thanks! There seems to be one last problem :) https://github.com/espanso/hub/actions/runs/3103995417

**Comment by jwliles** [comment]
I believe that I have fixed the errors.

**Comment by federico-terzi** [comment]
Looks great, thank you!

**Pull request merged**
