### PR TITLE
added currency-symbols

### PR DESCRIPTION
**Pull request by stibinator**
A package with currency symbols

### CODE REVIEW

**Comment by federico-terzi** [comment]
Hey @stibinator,

Looks amazing! Thank you for the help :) Could you please pull from the latest main and repush here? Otherwise the CI won't be able to run correctly

Thanks! :)

**Comment by smeech** [comment]
No `cmd`, `script`, `shell`, or malicious code.
No response to @federico-terzi's request 2½ years ago, otherwise could be merged,

**Comment by AucaCoyan** [comment]
Thank you!

**Comment by stibinator** [comment]
Thanks! Sorry I didn't do the things, I don't know how to git very well.

**Comment by smeech** [comment]
That's OK - me too!
We've found ways around Federico's constraint so it'll probably be merged soon.

**Comment by AucaCoyan** [comment]
Yes! don't worry next time, ask for help and we will do what we can, we are a very welcoming community ❤️

**Pull request merged**
