### PR TITLE
Updated actually-all-emojis & actually-all-emojis-spaces to latest version (v1.3.0)

### PR DESCRIPTION
**Pull request by jobiewong**
Main changes are as follows:
- Support for Emoji v15 (new emojis can be found [here](https://unicode.org/emoji/charts/emoji-versions.html))
- Fixed support for multi-character emojis
- Updated and more complete support for Discord/Slack short codes (list of short codes can be found [here](https://listemoji.com/cheat-sheet))
- Removed accents from all short codes to fix broken Unicode characters

### CODE REVIEW

**Comment by federico-terzi** [comment]
@jobiewong Thanks! Looks great :)

One thing before we can merge: the PR deletes/changes some of the files of the old version, but we want to keep them in the repo. Could you please change the PR to only add new files?

**Comment by jobiewong** [comment]
Thanks! Sorry it's taken me so long to get around to this. Let me know if there are any other issues.

**Comment by smeech** [comment]
No `cmd`, `script`, `shell` or malicious code.
Looks OK to merge.

**Comment by AucaCoyan** [comment]
Thank you!

**Pull request merged**
