### PR TITLE
Created a new Package for espanso - OASIS-IS Prompt Framework

### PR DESCRIPTION
**Pull request by Ryfter**
This is a mega-prompt framework form for prompting in ChatGPT, Claude and other chatbots.  It has two modes.  

1.  Using it in a URL bar or any text field it creates a prompt that will run in chatGPT.  This is the base version that allows users to get the full prompt in the form of a URL. This only works for ChatGPT.
2. This is meant to be used in any prompt box.  It does not include the URL, but just the text for the prompt.

### CODE REVIEW

**Comment by smeech** [comment]
That's an impressive piece of work, which passes all the automated checks.

No `script:`, `shell:`, `cmd:` or malicious code.

There's a lot of duplicated code between the two expansions, which could be shared using [Global Variables](https://espanso.org/docs/matches/extensions/#global-variables) or [Anchors and Aliases](https://espanso.org/docs/matches/extensions/#anchors-and-aliases)?

**Comment by Ryfter** [comment]
Thank you for your comments.  I'll dig into it, and optimize it.  I spent most of Sunday just getting that far. I appreciate you taking the time to give me feedback.

**Comment by smeech** [comment]
Thank you. That's neat.

`formo1` throws linter errors here, but works nevertheless.

To make it more tidy, I was playing around with trying to separate the **Interpretation** values list into an `echo:` global_var, but hadn't managed to make it work. 

Just one problem - the path version (currently `0.1.0`) needs to match the `version:` value in `_manifest.yml` (currently `0.1.1`), I'm afraid, before the CI will accept it.

Once this is fixed, and you're happy with the package, I'll merge it.

A few more typos, by line number:
  5. Evaluate
  6. available
  8. will
  17. & 30. additional

**Comment by smeech** [comment]
Thank you! That now passes all the CI checks. 

There are still a few typos - you might wish to correct the one at the top of README.md at least, as it's the one likely to be seen (the ones in the `package.yml` comments, less so)!

Let me know when you're happy, and I'll hit the Merge button.

**Pull request merged**
