### PR TITLE
Update `foreign-thanks` package

### PR DESCRIPTION
**Pull request by kopach**
Add new updated version (1.1.0) of foreign-thanks package

### CODE REVIEW

**Comment by kopach** [comment]
Hi @federico-terzi, could you, please, take a look and merge this. Thanks

**Comment by federico-terzi** [comment]
Hey @kopach,

Thanks for your help! Seems like there is an issue with the YAML formatting, please check the CI output for some guidance :)

Cheers :)

**Comment by kopach** [comment]
hey @federico-terzi,

Fixed all issues. Could you, please, take a look once again?
Thanks

**Comment by kopach** [comment]
hi @federico-terzi , would you mind to take a look on this, please?

**Comment by kopach** [comment]
hi @federico-terzi , any chance to merge this? All checks passed

**Comment by federico-terzi** [comment]
Looks amazing, thanks 🚀 Sorry for the late reply

**Pull request merged**
