### PR TITLE
Add `foreign-greetings` package

### PR DESCRIPTION
**Pull request by kopach**

### CODE REVIEW

**Comment by kopach** [comment]
hi @federico-terzi, could you, please also on this one, please? 
Thanks

**Comment by katrinleinweber** [comment]
Minor suggestions :-) There are already 2 `greetings-*` packages. How about:

- flipping the words around here to group with them, or
- calling it `foreign-hello` to clarify the difference in scope?

**Comment by kopach** [comment]
@katrinleinweber, my intention was to group it with `foreign-thanks`. I also picked `-greetings` just to allow potentially for both `hello` and `hi`. Right now, it only uses `hi`

**Comment by federico-terzi** [comment]
Looks great! Thanks :)

**Pull request merged**
