### PR TITLE
add autocomplete-en

### PR DESCRIPTION
**Pull request by 8-momo-8**
autocomplete for English language package for autocomplete English language, please add it to the hub

### CODE REVIEW

**Comment by federico-terzi** [comment]
@8-momo-8 Thanks! Two things before merging:
1. Everything should be inside a folder named as the version (see how other packages are structured)
2. We shouldn't have the `_pkgsource` file

:)

**Comment by 8-momo-8** [comment]
done ?

**Comment by 8-momo-8** [comment]
@federico-terzi 
done?

**Comment by federico-terzi** [comment]
Thanks! :)

**Pull request merged**
