### PR TITLE
Update better-typography (v0.1.3)

### PR DESCRIPTION
**Pull request by jwliles**
The leader key has been changed from `,` to `;` and in some cases to `;;`, and it has been added to some triggers where it had previously been missing.

### CODE REVIEW

**Comment by federico-terzi** [comment]
@jwliles Thanks! Looks great :)

One thing before we can merge: the PR deletes/changes some of the files of the old version, but we want to keep them in the repo. Could you please change the PR to only add new files?

**Comment by smeech** [comment]
No `cmd`, `script`, `shell` or malicious code.
No response to Federico's request a year ago - if we were to delete the PR file packages/better-typography/0.1.2/package.yml before merging, would that resolve the problem?

**Comment by AucaCoyan** [comment]
Thanks!

**Comment by smeech** [comment]
I note we've now lost v0.1.2.
Are you instituting a policy of discarding old versions?

**Comment by AucaCoyan** [comment]
No, sorry, that wasn't my intention. Just for this case I intend to speed up merges.
If it's needed, we can recover the old version from git history, but I'm planning to do it as I personally find it unnecessary.
What do you think?
I'll note this for the next espanso meeting 📝

**Comment by smeech** [comment]
I guessed the old version would be retrievable if necessary.
I don't see a need to keep them, and am not sure why Federico did, although he took the trouble to mention it in the docs _and_ build the facility to load old versions into the code for the espanso command-line options.

**Comment by smeech** [comment]
It does leave us with the problem of comparing new with old when inspecting the PRs' code, however.

**Pull request merged**
