### PR TITLE
feat: Git | New triggers of git commands

### PR DESCRIPTION
**Pull request by angelorpt**
Adding new triggers of git commands.

### CODE REVIEW

**Comment by federico-terzi** [comment]
@angelorpt Amazing, thanks! Could you please rename the `git.yml` file into `package.yml`? :) Otherwise it won't be a valid syntax

**Comment by smeech** [comment]
No `cmd`, `script`, `shell` or malicious code.
No response to Federico's request a year ago - presumably we could rename the file at this end prior to merge, if approved?

**Comment by AucaCoyan** [comment]
Yes, also all triggers begin with `git` so you won't do `git reset --hard` accidentally

**Comment by AucaCoyan** [comment]
CI failed, but because `main` is was broken at cfb9d8536cbb72c22d2fde41f9ebf0b23b13790f , not because this PR was wrong.
Squashing!

**Pull request merged**
