### PR TITLE
Add relative date expansion

### PR DESCRIPTION
**Pull request by f0rdprefect**
Simple regex match and python script to expand to relative dates in the future / past

### CODE REVIEW

**Comment by smeech** [comment]
Contains a long script.

```yml
  - regex: (?P<sign>[+-])(?P<value>\d+)(?P<unit>[dwmy])
    replace: "{{output}}"
    vars:
      - name: output
        type: script
        params:
          args:
            - python
            - -c
            - |
              from datetime import datetime, timedelta
              unit_to_days = {'d': 1, 'w': 7, 'm': 30, 'y': 365}
              print((datetime.now() + timedelta(days=int({{value}}) * unit_to_days['{{unit}}'] * (-1 if '{{sign}}' == '-' else 1))).strftime("%x"))
```
will do the same job.

**Comment by f0rdprefect** [comment]
I like simple so I close the pull request.

**Comment by smeech** [comment]
Sorry :cry:

**Comment by smeech** [comment]
It was pointed out to me that my version didn't allow for variable length months and years (yours did).

My three new versions are at: https://pastebin.com/8wy9dAU3 if you're interested.

Thank you for sending me down that rabbit hole!

**Comment by f0rdprefect** [comment]
Absolutely! thanks for letting me know.

**Pull request closed without merging**
