### PR TITLE
Basic GD&T symbols package 

### PR DESCRIPTION
**Pull request by vworp**

### CODE REVIEW

**Comment by federico-terzi** [comment]
Hey @vworp,

Sorry for the late reply! The package looks amazing, thank you for the help

Just one thing before we can merge, could you please:
* Pull from main `git pull origin main`
* Rename the package name (and the folder) to only contain lowercase letters, numbers and the hyphen `-`? :)
* Repush into this branch

Cheers :)

**Comment by vworp** [comment]
Hi Federico,
I'm not massively familiar with git, but I think I've done what you need :)

Max

**Comment by federico-terzi** [comment]
@vworp Thanks! It's almost perfect, one last thing before we can merge :) You need to change the package name inside the `manifest.yml` file into `gd-and-t` (it has to be the same name as the folder)

https://github.com/espanso/hub/actions/runs/2366504263#summary-6561485081

**Comment by federico-terzi** [comment]
@vworp Awesome! You deserve a Yoda https://github.com/espanso/hub/actions/runs/2373481248

**Pull request merged**
