### PR TITLE
add package kaomoji 0.2.0

### PR DESCRIPTION
**Pull request by citrusmunch**
hello, i made a kaomoji package! („• ᴗ •„)

### CODE REVIEW

**Comment by smeech** [comment]
A straightforward package of trigger/replace pairs. No shell, script, cmd, or malicious code.

Would you kindly rename the package "kaomoji" as in your heading, please? The "espanso-" prefix is self-evident. It'll mean renaming your path to `packages/kaomoji/0.2.0/` I'm afraid :frowning_face:.

**Comment by citrusmunch** [comment]
renamed! thanks for the swift reply :)

**Comment by smeech** [comment]
Thank you.

I'm intrigued by your liberal use of double quote marks `"`. Many people use them for [values](https://espanso.org/docs/matches/quotes/#double-quotes) but I haven't seen them around keys before, and didn't realise that would even work. I would have written your first trigger simply as:
```yml
  - replace: (* ^ ω ^)
    search_terms: ["'w", "'*"]
    trigger: ;kao joy 00
```
for example. Was there a reason for this?

I suspect the reason why some kao don't render in the search bar may be related to https://github.com/espanso/espanso/issues/974 and https://github.com/espanso/espanso/issues/2103

**Comment by citrusmunch** [comment]
hi @smeech, sorry to necro, but i wanted to thank you for the feedback!

for the double quotes i absolutely went overboard and didn't realize haha. initially i was using a `'kao` for the trigger (single quote) and i guess never undid that. also some of the replacements use quotes and i wanted to uniformly double quote all of them. hoping to clean all that up in the future.

and thanks for the hint on the rendering-- will take a look!! (⁀ᗢ⁀)

**Comment by smeech** [comment]
You're welcome. Many people are wedded to double-quotes around _replacement texts_, even when they're not necessary, which is fine, but was the reason for my [article](https://espanso.org/docs/matches/quotes) in the docs. I was just suprised to see them around `"trigger:"`, and `"replace:"` etc!

Best wishes, and thank you for your contribution!

**Pull request merged**
