### PR TITLE
Updates to brand-names & accented-words packages

### PR DESCRIPTION
**Pull request by joshjhall**

### CODE REVIEW

**Comment by federico-terzi** [comment]
Hey @joshjhall ,

Sorry for the late reply! Thank you for the help :)

Just one thing before we can merge, could you please:
* Pull from main `git pull origin main`
* Revert the changes in the 1.0.0 folder and create _a new_ folder called 1.0.2? That way all the package versions are downloadable :)
* Repush here

Cheers :)

**Comment by joshjhall** [comment]
@federico-terzi I somehow missed this message. Sorry about that. I've re-added the old version directories I'd accidentally deleted. Also included a large update to the accented words package.

Let me know if you need anything else.

**Comment by joshjhall** [comment]
@federico-terzi can you take a look at this PR when you've got a minute? Just want to confirm you're not waiting on me to fix something else here. Thanks!

**Comment by smeech** [comment]
Looks good.
No scripts or potentially malicious expansions.
Unless I have missed something, I think we could merge this.

**Comment by AucaCoyan** [comment]
Thanks @joshjhall for the submission and @smeech for the review!
I did a quick peek if some `cmd` or `shell` was overlooked and it's all good.
Merged!

**Pull request merged**
